path:
  logs: /var/project-glu/elasticsearch/logs
  data: /var/project-glu/elasticsearch/data

cluster:
  name: project-glu

node:
  name: project-glu1

http:
  port: 9209

transport:
  tcp:
    port: 9309

